#!/bin/bash

SELF=$(basename $(pwd))
IMG=minoc:latest
#IMG="images.opencadc.org/storage-inventory/minoc:1.0.7"

. $HOME/bin/docker-common-setup

\cp $HOME/config/cadc-storage-adapter-swift.properties config/
chmod 664 config/cadc-storage-adapter-swift.properties
echo "org.opencadc.inventory.storage.swift.SwiftStorageAdapter.segmentMinBytes = 10" >> config/cadc-storage-adapter-swift.properties

. $HOME/bin/docker-static-ip $SELF

\rm -f tomcat.log

PG=pg15-minoc
PGIP=$(docker-find-ip $PG)

CMD="docker run --rm --user tomcat:tomcat \
    --network=$DOCKER_NET --ip=$DOCKER_STATIC_IP \
    --add-host $HAP:$HAPIP \
    --env tomcat.connector.proxyName=$HAP \
    --add-host $PG:$PGIP \
    --volume=$(pwd)/config:/config:ro \
    --name $SELF $IMG"

echo $CMD
exec $CMD >& tomcat.log &

if [ "$1" = "-f" ]; then
    tail -100f tomcat.log
fi

