
org.opencadc.critwall.logging = info

org.opencadc.critwall.buckets = 0-f
org.opencadc.critwall.threads = 2

org.opencadc.critwall.locatorService=ivo://cadc.nrc.ca/raven

# inventory database settings
org.opencadc.inventory.db.SQLGenerator=org.opencadc.inventory.db.SQLGenerator
org.opencadc.critwall.db.schema=inventory
org.opencadc.critwall.db.username = cadmin
org.opencadc.critwall.db.password = pw-cadmin
org.opencadc.critwall.db.url=jdbc:postgresql://pg12db-minoc/content

# back end storage settings
org.opencadc.inventory.storage.StorageAdapter=org.opencadc.inventory.storage.fs.OpaqueFileSystemStorageAdapter


