#!/bin/bash

SELF=$(basename $(pwd))
IMG=luskan:si11

. $HOME/bin/docker-common-setup

. $HOME/bin/docker-static-ip $SELF

\cp $A/test-certificates/tmpops.pem config/tmpops.pem   

PG=pg15test
PGIP=$(grep $PG /etc/hosts | head -1 | awk '{print $1}')

CMD="docker run --rm --user tomcat:tomcat \
	--network=$DOCKER_NET --ip=$DOCKER_STATIC_IP \
	--add-host $PG:$PGIP \
	--add-host $HAP:$HAPIP \
	--env tomcat.connector.proxyName=$HAP \
        --volume=$(pwd)/config:/config:ro \
        --name $SELF $IMG"

echo $CMD

exec $CMD >& tomcat.log &

if [ "$1" = "-f" ]; then
    tail -100f tomcat.log
fi

