#!/bin/bash

SELF=$(basename $(pwd))
IMG=posix-mapper:latest
IMG="images.opencadc.org/platform/posix-mapper:0.3.2"

. $HOME/bin/docker-common-setup SRC

. $HOME/bin/docker-static-ip $SELF

PG=srcposixdb
PGIP=$(docker-find-ip $PG)

## YES: runs as root internally
CMD="docker run --rm --user root:root \
    --network=$DOCKER_NET --ip=$DOCKER_STATIC_IP \
    --add-host $HAP:$HAPIP \
    --env tomcat.connector.proxyName=$HAP \
    --add-host $PG:$PGIP \
    --volume=$(pwd)/config:/config:ro \
    --name $SELF $IMG"

echo $CMD

exec $CMD >& tomcat.log &

if [ "$1" = "-f" ]; then
    exec tail -100f tomcat.log
fi

