#!/bin/bash

SELF=$(basename $(pwd))
IMG=reg:latest
IMG="images.opencadc.org/core/reg:1.2.1"

. $HOME/bin/docker-common-setup

. $HOME/bin/docker-static-ip $SELF

echo "mangling reg-resource-caps config..."
cat config/reg-resource-caps.base | sed "s/PROXYNAME/$HAP/g" > config/reg-resource-caps.properties
grep 'ivo://opencadc.org/reg' config/reg-resource-caps.properties
echo "..."

CMD="docker run --rm --user tomcat:tomcat \
	--network=$DOCKER_NET --ip=$DOCKER_STATIC_IP \
	--add-host $HAP:$HAPIP \
	--env tomcat.connector.proxyName=$HAP \
	--volume=$(pwd)/config:/config:ro \
	--volume=$(pwd)/cadc-content:/content:ro \
        --name $SELF $IMG"

echo $CMD

exec $CMD >& tomcat.log &

if [ "$1" = "-f" ]; then
    tail -100f tomcat.log
fi

