#!/bin/bash

SELF=$(basename $(pwd))
IMG=vault:latest
#IMG="images.opencadc.org/storage-inventory/vault:1.0.16"

. $HOME/bin/docker-common-setup

. $HOME/bin/docker-static-ip $SELF

PG=vault-site-db
PGIP=$(docker-find-ip $PG)

CMD="docker run --rm --user tomcat:tomcat \
    --network=$DOCKER_NET --ip=$DOCKER_STATIC_IP \
    --add-host $HAP:$HAPIP \
    --env tomcat.connector.proxyName=$HAP \
    --add-host $PG:$PGIP \
    --volume=$(pwd)/config:/config:ro \
    --name $SELF $IMG"

echo $CMD
exec $CMD >& tomcat.log &

if [ "$1" = "-f" ]; then
    tail -100f tomcat.log
fi

