#!/bin/bash

SELF=$(basename $(pwd))
IMG=minoc:latest

. $HOME/bin/docker-common-setup

. $HOME/work/bin/docker-static-ip $SELF

DATADIR=$(pwd)/storage
mkdir -p $DATADIR
setfacl -m user:8675309:rwx $DATADIR

PG=vault-site-db
PGIP=$(lxc list | grep $PG | awk '{print $6}')

CMD="docker run --rm --user tomcat:tomcat \
    --network=$DOCKER_NET --ip=$DOCKER_STATIC_IP \
    --add-host $HAP:$HAPIP \
    --add-host $PG:$PGIP \
    --volume=$(pwd)/config:/config:ro \
    --volume=${DATADIR}:/data:rw \
    --name $SELF $IMG"

echo $CMD
exec $CMD >& tomcat.log &

if [ "$1" = "-f" ]; then
    tail -100f tomcat.log
fi

