#!/bin/bash

SELF=tantar
IMG=tantar:latest
#IMG="images.opencadc.org/storage-inventory/tantar:1.1.0"

. $HOME/bin/docker-common-setup

. $HOME/bin/docker-static-ip $SELF

DATADIR=$(pwd)/storage
mkdir -p $DATADIR
setfacl -m user:8675309:rwx $DATADIR

\cp ~/.ssl/pdowler.pem config/cadcproxy.pem

PG=pg15-si-metasync
PGIP=$(docker-find-ip $PG)

CMD="docker run --rm --user opencadc:opencadc \
	--network=$DOCKER_NET --ip=$DOCKER_STATIC_IP \
	--add-host $HAP:$HAPIP \
	--add-host $PG:$PGIP \
	--volume=$(pwd)/config:/config:ro \
	--volume=$DATADIR:/data:rw \
	--name  $SELF $IMG"

echo $CMD

$CMD
