#!/bin/bash

SELF=$(basename $(pwd))
IMG=cavern:latest
#IMG="images.opencadc.org/platform/cavern:0.7.5"

. $HOME/bin/docker-static-ip $SELF
echo "DOCKER_STATIC_IP: $DOCKER_STATIC_IP"
echo "      DOCKER_NET: $DOCKER_NET"

cat /home/pdowler/work/etc/RsaSignaturePub.key > config/RsaSignaturePub.key
\cp ~/work/test-certificates/servops.pem config/cadcproxy.pem

\rm -f tomcat.log && touch tomcat.log

DATADIR=/data/local/cavern
if [ ! -d $DATADIR ]; then
    echo "not found: DATADIR=$DATADIR"
    exit 1
fi
EXTRADIR=/data/local/junk

HAP=haproxy.cadc.dao.nrc.ca
HAPIP=$(grep $HAP /etc/hosts | awk '{print $1}')

PG=caverndb
PGIP=$(lxc list | grep $PG | awk '{print $6}')

## YES: runs as root internally
CMD="docker run --rm --user root:root \
    --network=$DOCKER_NET --ip=$DOCKER_STATIC_IP \
    --add-host $HAP:$HAPIP \
    --add-host $PG:$PGIP \
    --volume=$(pwd)/config:/config:ro \
    --volume=${DATADIR}:/data:rw \
    --volume=${EXTRADIR}:/extra:ro \
    --name $SELF $IMG"

echo $CMD

exec $CMD >& tomcat.log &

if [ "$1" = "-f" ]; then
    tail -100f tomcat.log
fi

