#!/bin/bash

SELF=$(basename $(pwd))
IMG=cavern:latest
#IMG="images.opencadc.org/platform/cavern:0.9.2"

. $HOME/bin/docker-common-setup

. $HOME/bin/docker-static-ip $SELF

echo "append posixmapper config..."
echo "http://www.opencadc.org/std/posix#group-mapping-0.1 = ivo://cadc.nrc.ca/gms" >> config/cadc-registry.properties
echo "http://www.opencadc.org/std/posix#user-mapping-0.1 = ivo://cadc.nrc.ca/gms" >> config/cadc-registry.properties

DATADIR=$(pwd)/storage
mkdir -p $DATADIR
setfacl -m user:8675309:rwx $DATADIR
EXTRADIR=$(pwd)/extra
mkdir -p $EXTRADIR
setfacl -m user:8675309:rwx $DATADIR

PG=caverndb
PGIP=$(docker-find-ip $PG)

## YES: runs as root internally
CMD="docker run --rm --user root:root \
    --network=$DOCKER_NET --ip=$DOCKER_STATIC_IP \
    --add-host $HAP:$HAPIP \
    --env tomcat.connector.proxyName=$HAP \
    --add-host $PG:$PGIP \
    --volume=$(pwd)/config:/config:ro \
    --volume=${DATADIR}:/data:rw \
    --volume=${EXTRADIR}:/extra:ro \
    --name $SELF $IMG"

echo $CMD

exec $CMD >& tomcat.log &

if [ "$1" = "-f" ]; then
    tail -100f tomcat.log
fi

