#!/bin/bash

SELF=$(basename $(pwd))
IMG="youcat:latest"
#IMG="images.opencadc.org/core/youcat:0.7.5"

. $HOME/work/bin/docker-static-ip $SELF
echo "DOCKER_STATIC_IP: $DOCKER_STATIC_IP"
echo "      DOCKER_NET: $DOCKER_NET"

$HOME/bin/docker-common-setup
\cp ~/work/test-certificates/tmpops.pem config/tmpops.pem

\rm -f tomcat.log && touch tomcat.log

HAP=haproxy.cadc.dao.nrc.ca
HAPIP=$(grep $HAP /etc/hosts | awk '{print $1}')

PG=youcatdb
PGIP=$(docker-find-ip $PG)

CMD="docker run --rm --user tomcat:tomcat \
	--network=$DOCKER_NET --ip=$DOCKER_STATIC_IP \
	--add-host $HAP:$HAPIP \
        --add-host $PG:$PGIP \
	--volume=$(pwd)/config:/config:ro \
        --name $SELF $IMG"

echo $CMD

$CMD >& tomcat.log &

if [ "$1" = "-f" ]; then
    exec tail -100f tomcat.log
fi

