
org.opencadc.torkeep.grantProvider = ivo://opencadc.org/baldur

org.opencadc.torkeep.archiveOperator = CN=cadcauthtest2_ff0,OU=cadc,O=hia,C=ca
org.opencadc.torkeep.metaSyncOperator = CN=cadcregtest1_b5d,OU=cadc,O=hia,C=ca

org.opencadc.torkeep.collection = IRIS
IRIS.obsIdentifierPrefix = caom:
IRIS.basePublisherID = ivo://opencadc.org/

org.opencadc.torkeep.collection = TEST
TEST.obsIdentifierPrefix = caom:
TEST.basePublisherID = ivo://opencadc.org/
#TEST.validationPolicy = core-validation.properties

org.opencadc.torkeep.collection = IVOTEST
IVOTEST.obsIdentifierPrefix = ivo://opencadc.org/
IVOTEST.basePublisherID = ivo://opencadc.org/

## onyx TDM to CAOM testing
org.opencadc.torkeep.collection = RACS
RACS.obsIdentifierPrefix = caom:
RACS.basePublisherID = ivo://opencadc.org/

org.opencadc.torkeep.collection = SKAO
SKAO.obsIdentifierPrefix = caom:
SKAO.basePublisherID = ivo://opencadc.org/

org.opencadc.torkeep.collection = sdss
sdss.obsIdentifierPrefix = caom:
sdss.basePublisherID = ivo://opencadc.org/


