
org.opencadc.tap.tmp.StorageManager = org.opencadc.tap.tmp.TempStorageManager

## fs 
org.opencadc.tap.tmp.TempStorageManager.baseURL = https://haproxy.cadc.dao.nrc.ca/luskan/results
org.opencadc.tap.tmp.TempStorageManager.baseStorageDir = /var/tmp/luskan

## http impl
#org.opencadc.tap.tmp.HttpStorageManager.baseURL = https://haproxy.cadc.dao.nrc.ca/minoc/files/tmp:luskan
#org.opencadc.tap.tmp.HttpStorageManager.certificate = tmpops.pem

