## enable setting system props with environment
org.apache.tomcat.util.digester.PROPERTY_SOURCE=org.apache.tomcat.util.digester.EnvironmentPropertySource

tomcat.connector.connectionTimeout=20000
tomcat.connector.keepAliveTimeout=20000
tomcat.connector.secure=true
tomcat.connector.scheme=https
#tomcat.connector.proxyName=haproxy.cadc.dao.nrc.ca
tomcat.connector.proxyPort=443

org.opencadc.luskan.tapadm.maxActive=1
org.opencadc.luskan.tapadm.username=tapadm
org.opencadc.luskan.tapadm.password=pw-tapadm
org.opencadc.luskan.tapadm.url=jdbc:postgresql://pg15test/cadctest

org.opencadc.luskan.uws.maxActive=1
org.opencadc.luskan.uws.username=tapadm
org.opencadc.luskan.uws.password=pw-tapadm
org.opencadc.luskan.uws.url=jdbc:postgresql://pg15test/cadctest

org.opencadc.luskan.query.maxActive=1
org.opencadc.luskan.query.username=tapuser
org.opencadc.luskan.query.password=pw-tapuser
org.opencadc.luskan.query.url=jdbc:postgresql://pg15test/cadctest

## enable support for haproxy SSL termination + pass client cert
ca.nrc.cadc.auth.PrincipalExtractor.enableClientCertHeader=true

ca.nrc.cadc.auth.IdentityManager = ca.nrc.cadc.ac.ACIdentityManager

