# service identity
#org.opencadc.luskan.resourceID=ivo://cadc.nrc.ca/luskan

org.opencadc.luskan.isStorageSite=true

org.opencadc.luskan.allowedGroup=ivo://cadc.nrc.ca/gms?CADC

## dev use only
org.opencadc.luskan.disableQueryFilters=true

