# log level
org.opencadc.icewind.logging=info

#org.opencadc.icewind.retrySkipped = true
#org.opencadc.icewind.validate = true

# Source repository service
org.opencadc.icewind.repoService=ivo://cadc.nrc.ca/ams
#org.opencadc.icewind.repoService=ivo://mast.stsci.edu/caom2repo

# The collections to sync, one collection per line
org.opencadc.icewind.collection=IRIS
org.opencadc.icewind.collection=CGPS
org.opencadc.icewind.collection=VGPS

# Maximum number of seconds to pause between runs
org.opencadc.icewind.maxIdle=90

# Destination caom2 database settings
org.opencadc.icewind.caom.schema=caom2
org.opencadc.icewind.caom.username=cadmin
org.opencadc.icewind.caom.password=pw-cadmin
org.opencadc.icewind.caom.url=jdbc:postgresql://caom2db/content

# Base for generating Plane publisherID values
org.opencadc.icewind.basePublisherID=ivo://opencadc.org/

# Optional - exit after processing collections once
org.opencadc.icewind.exitWhenComplete=true

