#!/bin/bash

SELF=$(basename $(pwd))
IMG="baldur:latest"

. $HOME/bin/docker-common-setup

. $HOME/bin/docker-static-ip $SELF

CMD="docker run --rm --user tomcat:tomcat \
	--network=$DOCKER_NET --ip=$DOCKER_STATIC_IP \
	--add-host $HAP:$HAPIP \
	--env tomcat.connector.proxyName=$HAP \
	--volume=$(pwd)/config:/config:ro \
        --name $SELF $IMG"

echo $CMD

$CMD >& tomcat.log &

if [ "$1" = "-f" ]; then
    exec tail -100f tomcat.log
fi

