# configure the admin user: admin user can create a schema via the REST API
# for StandardIdentityManager and OIDC, this is: {issuer} {sub} 
org.opencadc.youcat.adminUser = https://ska-iam.stfc.ac.uk/ 211b77e1-686a-4116-bcff-1b2a85c442e1

# (optional) configure schema creation in the database (default: false)
# if true, the admin call to create a schema will try to create it in the db
#          and add it to tap_schema
# if false, the admin call will only add the schema to the tap_schema
#           and assume it exists
org.opencadc.youcat.createSchemaInDB = true

