tomcat.connector.connectionTimeout=20000
tomcat.connector.keepAliveTimeout=20000
tomcat.connector.secure=true
tomcat.connector.scheme=https
#tomcat.connector.proxyName=haproxy.cadc.dao.nrc.ca
tomcat.connector.proxyPort=443

## enable setting system props with environment
org.apache.tomcat.util.digester.PROPERTY_SOURCE=org.apache.tomcat.util.digester.EnvironmentPropertySource

## enable support for haproxy SSL termination + pass client cert
ca.nrc.cadc.auth.PrincipalExtractor.enableClientCertHeader=true

## configure CADC IM
ca.nrc.cadc.auth.IdentityManager=ca.nrc.cadc.ac.ACIdentityManager

#ca.nrc.cadc.util.Log4jInit.messageOnly=true

# database connection pools
org.opencadc.vault.uws.maxActive=1
org.opencadc.vault.uws.username=tapadm
org.opencadc.vault.uws.password=pw-tapadm
org.opencadc.vault.uws.url=jdbc:postgresql://vault-site-db/content

org.opencadc.vault.nodes.maxActive=2
org.opencadc.vault.nodes.username=cadmin
org.opencadc.vault.nodes.password=pw-cadmin
org.opencadc.vault.nodes.url=jdbc:postgresql://vault-site-db/content

org.opencadc.vault.inventory.maxActive=0
org.opencadc.vault.inventory.username=cadmin
org.opencadc.vault.inventory.password=pw-cadmin
org.opencadc.vault.inventory.url=jdbc:postgresql://vault-site-db/content

