#!/bin/bash

SELF=$(basename $(pwd))
IMG=minoc:latest
#IMG="images.opencadc.org/storage-inventory/minoc:1.0.7"

$HOME/bin/docker-common-setup

. $HOME/bin/docker-static-ip $SELF
echo "DOCKER_STATIC_IP: $DOCKER_STATIC_IP"
echo "      DOCKER_NET: $DOCKER_NET"

\rm -f tomcat.log

DATADIR=$(pwd)/storage
mkdir -p $DATADIR
setfacl -m user:8675309:rwx $DATADIR

\cp ~/work/test-certificates/servops.pem config/cadcproxy.pem
   
PG=pg15-minoc
PGIP=$(docker-find-ip $PG)

HAP=haproxy.cadc.dao.nrc.ca
HAPIP=$(grep $HAP /etc/hosts | awk '{print $1}')


CMD="docker run --rm --user tomcat:tomcat \
    --network=$DOCKER_NET --ip=$DOCKER_STATIC_IP \
    --add-host $HAP:$HAPIP \
    --add-host $PG:$PGIP \
    --volume=$(pwd)/config:/config:ro \
    --volume=${DATADIR}:/data:rw \
    --name $SELF $IMG"

echo $CMD
exec $CMD >& tomcat.log &

if [ "$1" = "-f" ]; then
    tail -100f tomcat.log
fi

