# {scheme} = {fully qualified implementation}

# default resolver for everything in CADC archive (storage-inventory)
* = ca.nrc.cadc.caom2.artifact.resolvers.CadcResolver

# CADC scraped and created metadata but files are only at the source archive
chandra=ca.nrc.cadc.caom2.artifact.resolvers.ChandraResolver
noao=ca.nrc.cadc.caom2.artifact.resolvers.NoaoResolver
sdss=ca.nrc.cadc.caom2.artifact.resolvers.SdssResolver
subaru=ca.nrc.cadc.caom2.artifact.resolvers.SubaruResolver
xmm=ca.nrc.cadc.caom2.artifact.resolvers.XmmResolver

