tomcat.connector.connectionTimeout=20000
tomcat.connector.keepAliveTimeout=20000
tomcat.connector.secure=true
tomcat.connector.scheme=https
tomcat.connector.proxyName=haproxy.cadc.dao.nrc.ca
tomcat.connector.proxyPort=443

## enable support for haproxy SSL termination + pass client cert
ca.nrc.cadc.auth.PrincipalExtractor.enableClientCertHeader=true

## enable CADC IdentityManager
ca.nrc.cadc.auth.IdentityManager=ca.nrc.cadc.ac.ACIdentityManager

#ca.nrc.cadc.util.Log4jInit.messageOnly=true

# database connection pools
org.opencadc.argus.uws.maxActive=1
org.opencadc.argus.uws.username=tapadm
org.opencadc.argus.uws.password=pw-tapadm
org.opencadc.argus.uws.url=jdbc:postgresql://caom2db/content

org.opencadc.argus.tapadm.maxActive=1
org.opencadc.argus.tapadm.username=tapadm
org.opencadc.argus.tapadm.password=pw-tapadm
org.opencadc.argus.tapadm.url=jdbc:postgresql://caom2db/content

org.opencadc.argus.query.maxActive=1
org.opencadc.argus.query.username=tapuser
org.opencadc.argus.query.password=pw-tapuser
org.opencadc.argus.query.url=jdbc:postgresql://caom2db/content

