#!/bin/bash

SELF=$(basename $(pwd))
IMG="sc2meta:latest"

$HOME/bin/docker-common-setup

. $HOME/bin/docker-static-ip $SELF
echo "DOCKER_STATIC_IP: $DOCKER_STATIC_IP"
echo "      DOCKER_NET: $DOCKER_NET"

HAP=haproxy.cadc.dao.nrc.ca
HAPIP=$(grep $HAP /etc/hosts | awk '{print $1}')

PG=pg15-argus
PGIP=$(lxc list | grep $PG | awk '{print $6}')

CMD="docker run --rm --user tomcat:tomcat \
	--network=$DOCKER_NET --ip=$DOCKER_STATIC_IP \
	--add-host $HAP:$HAPIP \
    	--add-host $PG:$PGIP \
	--volume=$(pwd)/config:/config:ro \
        --name $SELF $SELF:latest"

echo $CMD

sudo $CMD >& tomcat.log &

if [ "$1" = "-f" ]; then
    exec tail -100f tomcat.log
fi

