#!/bin/bash

IMG=cadc-postgresql-dev:latest
#IMG="images.opencadc.org/dev-only/cadc-postgresql-dev:1"

INIT=$1
DBNAME=$2

if [ -z "$DBNAME" ]; then
    echo "usage: $0 {init-file} {db container name}"
    exit 1
fi

DOCKER_NET=docker26
DBIP=$(DBCONTAINER=etc docker-find-ip $DBNAME)

CMD="docker run -d \
    --network=$DOCKER_NET --ip=$DBIP \
    --mount type=bind,source=$(pwd)/${INIT},target=/config/init-content-schemas.sh,readonly \
    --name $DBNAME $IMG"

echo $CMD

eval $CMD

