# registry bootstrap
# as of cadc-registry-1.9.0 multiple reg services are supported
ca.nrc.cadc.reg.client.RegistryClient.baseURL=https://haproxy.cadc.dao.nrc.ca/reg
ca.nrc.cadc.reg.client.RegistryClient.baseURL=https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg

# <base standardID> = <authority>
ivo://ivoa.net/std/GMS#search-1.0 = ivo://cadc.nrc.ca/gms

#ivo://ivoa.net/std/GMS#search-0.1 = ivo://cadc.nrc.ca/gms

ivo://ivoa.net/std/GMS#groups-1.0 = ivo://cadc.nrc.ca/gms
ivo://ivoa.net/std/UMS#users-0.1 = ivo://cadc.nrc.ca/gms
ivo://ivoa.net/std/UMS#login-0.1 = ivo://cadc.nrc.ca/gms

ivo://ivoa.net/sso#tls-with-password = ivo://cadc.nrc.ca/gms

ivo://ivoa.net/std/CDP#proxy-1.0 = ivo://cadc.nrc.ca/cred
#ivo://ivoa.net/std/CDP#proxy-1.0 = ivo://opencadc.org/cred
#ivo://ivoa.net/std/CDP#proxy-1.0 = ivo://not-such-auth/cred


