## filesystem
org.opencadc.tap.tmp.StorageManager = org.opencadc.tap.tmp.TempStorageManager
org.opencadc.tap.tmp.TempStorageManager.baseURL = https://haproxy.cadc.dao.nrc.ca/youcat/tmp
org.opencadc.tap.tmp.TempStorageManager.baseStorageDir = /var/tmp/youcat

## http service
#org.opencadc.tap.tmp.StorageManager = org.opencadc.tap.tmp.HttpStorageManager
#org.opencadc.tap.tmp.HttpStorageManager.baseURL = https://haproxy.cadc.dao.nrc.ca/minoc/files/tmp:youcat
#org.opencadc.tap.tmp.HttpStorageManager.certificate = tmpops.pem

