tomcat.connector.connectionTimeout=20000
tomcat.connector.keepAliveTimeout=20000
tomcat.connector.secure=true
tomcat.connector.scheme=https
tomcat.connector.proxyName=haproxy.cadc.dao.nrc.ca
tomcat.connector.proxyPort=443

# connection pools
org.opencadc.youcat.tapadm.maxActive=1
org.opencadc.youcat.tapadm.username=tapadm
org.opencadc.youcat.tapadm.password=pw-tapadm
org.opencadc.youcat.tapadm.url=jdbc:postgresql://youcatdb/content

org.opencadc.youcat.tapuser.maxActive=1
org.opencadc.youcat.tapuser.username=tapuser
org.opencadc.youcat.tapuser.password=pw-tapuser
org.opencadc.youcat.tapuser.url=jdbc:postgresql://youcatdb/content

org.opencadc.youcat.uws.maxActive=1
org.opencadc.youcat.uws.username=tapadm
org.opencadc.youcat.uws.password=pw-tapadm
org.opencadc.youcat.uws.url=jdbc:postgresql://youcatdb/content

## enable support for haproxy SSL termination + pass client cert
ca.nrc.cadc.auth.PrincipalExtractor.enableClientCertHeader=true

# CADC AAI system
ca.nrc.cadc.auth.IdentityManager=ca.nrc.cadc.ac.ACIdentityManager

ca.nrc.cadc.util.Log4jInit.messageOnly=true

