# (optional) configure the admin user
org.opencadc.youcat.adminUser = CN=patrick dowler,OU=nrc-cnrc.gc.ca,O=grid,C=ca

# (optional) schema creation in the database (default: false)
org.opencadc.youcat.createSchemaInDB = true

org.opencadc.youcat.metadataValidation = strict

