#!/bin/bash

SELF=$(basename $(pwd))
IMG=torkeep:caom25

$HOME/bin/docker-common-setup

. $HOME/bin/docker-static-ip $SELF
echo "DOCKER_STATIC_IP: $DOCKER_STATIC_IP"
echo "      DOCKER_NET: $DOCKER_NET"

PG=torkeep25db
PGIP=$(docker-find-ip $PG)

HAP=haproxy.cadc.dao.nrc.ca
HAPIP=$(grep $HAP /etc/hosts | awk '{print $1}')

CMD="docker run --rm --user tomcat:tomcat \
	--network=$DOCKER_NET --ip=$DOCKER_STATIC_IP \
	--add-host $HAP:$HAPIP \
    	--add-host $PG:$PGIP \
	--volume=$(pwd)/config:/config:ro \
        --name $SELF $IMG"

echo $CMD

$CMD >& tomcat.log &

if [ "$1" = "-f" ]; then
    exec tail -100f tomcat.log
fi

