#!/bin/bash

SELF=$(basename $(pwd))
IMG=raven:si11

. $HOME/bin/docker-common-setup

. $HOME/bin/docker-static-ip $SELF

PG=pg15test
PGIP=$(grep $PG /etc/hosts | grep -v '-' | awk '{print $1}')

CMD="docker run --rm --user tomcat:tomcat \
    --network=$DOCKER_NET --ip=$DOCKER_STATIC_IP \
    --add-host $HAP:$HAPIP \
    --env tomcat.connector.proxyName=$HAP \
    --add-host $PG:$PGIP \
    --volume=$(pwd)/config:/config:ro \
    --name $SELF $IMG"

echo $CMD
$CMD >& tomcat.log &

if [ "$1" = "-f" ]; then
    exec tail -100f tomcat.log
fi

