#!/bin/bash

SELF=$(basename $(pwd))
IMG=icewind:latest

RUSER=opencadc:opencadc

$HOME/bin/docker-common-setup

\rm -f config/cadcproxy.pem
\cp $HOME/.ssl/cadcproxy.pem config/

PG=caom2db
PGIP=$(lxc list | grep $PG | awk '{print $6}')

PG=caom2db

CMD="docker run --rm --user $RUSER \
	--add-host $PG:$PGIP \
	--volume=$(pwd)/config:/config:ro \
	--name  $SELF $IMG"

echo $CMD

$CMD

