
# CAOM TAP service
org.opencadc.bifrost.queryService = ivo://opencadc.org/argus

# artifact locator service
org.opencadc.bifrost.locatorService = ivo://cadc.nrc.ca/global/raven

# read grant providers (optional)
org.opencadc.bifrost.readGrantProvider = ivo://cadc.nrc.ca/global/baldur

