tomcat.connector.connectionTimeout=20000
tomcat.connector.keepAliveTimeout=20000
tomcat.connector.secure=true
tomcat.connector.scheme=https
tomcat.connector.proxyName=haproxy.cadc.dao.nrc.ca
tomcat.connector.proxyPort=443

## enable support for haproxy SSL termination + pass client cert
ca.nrc.cadc.auth.PrincipalExtractor.enableClientCertHeader=true

## enable CADC IdentityManager
ca.nrc.cadc.auth.IdentityManager=ca.nrc.cadc.ac.ACIdentityManager

#ca.nrc.cadc.util.Log4jInit.messageOnly=true

org.opencadc.bifrost.uws.maxActive=1
org.opencadc.bifrost.uws.username=tapadm
org.opencadc.bifrost.uws.password=pw-tapadm
org.opencadc.bifrost.uws.url=jdbc:postgresql://caom2db/content


