#!/bin/bash

BASE=$(git rev-parse --show-toplevel)

echo "import common config..."
if [[ "$1" == "SRC" ]]; then
  CF=$BASE/src-config
else
  CF=$BASE/config
fi
rsync -avuc $CF/ config/



echo "local haproxy setup..."
HAP=$(grep haproxy /etc/hosts | grep -v haproxy.local | awk '{print $2}')
HAPIP=$(grep haproxy /etc/hosts | grep -v haproxy.local | awk '{print $1}')
echo "$HAP -> $HAPIP"
export HAP HAPIP

echo "adding local reg..."
LOC="https://$HAP/reg"
sed -i "s|LOCALREG|$LOC|g" config/cadc-registry.properties

if [ "$1" == "nosecrets" ]; then
  exit 0
fi

echo "import secrets..."
\cp ~/work/etc/RsaSignaturePub.key config/
\cp ~/work/test-certificates/servops.pem config/cadcproxy.pem

