#!/bin/bash

BASE=$(git rev-parse --show-toplevel)

echo "import common config..."
rsync -avuc $BASE/config/ config/

if [ "$1" == "nosecrets" ]; then
  exit 0
fi

echo "import secrets..."
\cp ~/work/etc/RsaSignaturePub.key config/
\cp ~/work/test-certificates/servops.pem config/cadcproxy.pem

