#!/bin/bash

HAP=$(grep haproxy /etc/hosts | grep -v haproxy.local | awk '{print $2}')

CMD="curl -s https://$HAP/reg/resource-caps"

RES=$1
if [[ ! -z "$RES" ]]; then
    CMD="$CMD | grep -i '$RES[ ]*='"
fi

eval $CMD

