
org.opencadc.torkeep.grantProvider = ivo://opencadc.org/baldur

org.opencadc.torkeep.collection = IRIS
IRIS.basePublisherID = ivo://opencadc.org/
#IRIS.computeMetadata = false 
#IRIS.proposalGroup = false

org.opencadc.torkeep.collection = TEST
TEST.basePublisherID = ivo://opencadc.org/
TEST.computeMetadata = true

