
# optional
#org.opencadc.torkeep.grantProvider =

# operations permissions: read-write (optional)
## Patrick Dowler test client
org.opencadc.torkeep.archiveOperator = https://ska-iam.stfc.ac.uk/ 26273543-c0d0-49c6-9d10-5b694a4cb759
## Michael Johnson test client
org.opencadc.torkeep.archiveOperator = https://ska-iam.stfc.ac.uk/ 9974b89d-ae81-4288-8b3a-3a42e7c65d98

# operations permissions: read-only
#org.opencadc.torkeep.metaSyncOperator = 

org.opencadc.torkeep.collection = SKA
SKA.basePublisherID = ivo://skao.int/
SKA.obsIdentifierPrefix = ivo://skao.int/
SKA.validationPolicy = SKA-extended-validation.txt

org.opencadc.torkeep.collection = TEST
TEST.basePublisherID = ivo://skao.int/
TEST.obsIdentifierPrefix = caom:

