
org.opencadc.critwall.logging = info

org.opencadc.critwall.buckets = 0-f
org.opencadc.critwall.threads = 8

org.opencadc.critwall.locatorService=ivo://cadc.nrc.ca/global/raven

# inventory database settings
org.opencadc.inventory.db.SQLGenerator=org.opencadc.inventory.db.SQLGenerator
org.opencadc.critwall.inventory.schema=inventory
org.opencadc.critwall.inventory.username = cadmin
org.opencadc.critwall.inventory.password = pw-cadmin
org.opencadc.critwall.inventory.url=jdbc:postgresql://pg15-si-metasync/content

# back end storage settings
org.opencadc.inventory.storage.StorageAdapter=org.opencadc.inventory.storage.fs.OpaqueFileSystemStorageAdapter


