org.opencadc.ratik.logging = info

# inventory database settings
org.opencadc.inventory.db.SQLGenerator=org.opencadc.inventory.db.SQLGenerator
org.opencadc.ratik.inventory.schema=inventory
org.opencadc.ratik.inventory.username=cadmin
org.opencadc.ratik.inventory.password=pw-cadmin
org.opencadc.ratik.inventory.url=jdbc:postgresql://pg15-si-metasync/content

org.opencadc.ratik.queryService = ivo://cadc.nrc.ca/global/luskan
#org.opencadc.ratik.queryService = ivo://opencadc.org/global/luskan

org.opencadc.ratik.trackSiteLocations = false
org.opencadc.ratik.artifactSelector = filter 

org.opencadc.ratik.buckets=0-f

#org.opencadc.ratik.enableRowCounterFeature = true
