
org.opencadc.tantar.reportOnly = false 

org.opencadc.tantar.logging = info 

org.opencadc.tantar.buckets = 0-f

# inventory database settings
org.opencadc.inventory.db.SQLGenerator=org.opencadc.inventory.db.SQLGenerator
org.opencadc.tantar.inventory.schema = inventory
org.opencadc.tantar.inventory.username = cadmin
org.opencadc.tantar.inventory.password = pw-cadmin
org.opencadc.tantar.inventory.url = jdbc:postgresql://pg15-si-metasync/content

org.opencadc.tantar.policy.ResolutionPolicy = InventoryIsAlwaysRight

org.opencadc.inventory.storage.StorageAdapter=org.opencadc.inventory.storage.fs.OpaqueFileSystemStorageAdapter

