#!/bin/bash

SELF=$(basename $(pwd))
IMG=cred:latest

. $HOME/bin/docker-common-setup

\cp ~/work/etc/signcert.pem config/

. $HOME/work/bin/docker-static-ip $SELF

CMD="docker run --rm --user tomcat:tomcat \
	--network=$DOCKER_NET --ip=$DOCKER_STATIC_IP \
	--add-host $HAP:$HAPIP \
	--volume=$(pwd)/config:/config:ro \
        --name $SELF $IMG"

echo $CMD

exec $CMD >& tomcat.log &

if [ "$1" = "-f" ]; then
    tail -100f tomcat.log
fi

