org.opencadc.baldur.grantExpiry = 60

org.opencadc.baldur.allowedUser = CN=servops_4a2,OU=cadc,O=hia,C=ca 
org.opencadc.baldur.allowedUser = CN=cadcauthtest1_24c,OU=cadc,O=hia,C=ca

org.opencadc.baldur.entry = BALDUR
BALDUR.pattern = ^baldur:TEST/.*
BALDUR.readOnlyGroup = ivo://cadc.nrc.ca/gms?Test-Read
BALDUR.readWriteGroup = ivo://cadc.nrc.ca/gms?Test-Write
BALDUR.anon = true

org.opencadc.baldur.entry = CAOM-TEST
CAOM-TEST.pattern = ^caom:TEST/.*
CAOM-TEST.readWriteGroup = ivo://cadc.nrc.ca/gms?caom2TestGroupWrite

org.opencadc.baldur.entry = IVO-TEST
IVO-TEST.pattern = ^ivo://opencadc.org/IVOTEST?.*
IVO-TEST.readWriteGroup = ivo://cadc.nrc.ca/gms?caom2TestGroupWrite

org.opencadc.baldur.entry = test
test.pattern = ^test:.*
test.anon = true 
test.readWriteGroup = ivo://cadc.nrc.ca/gms?CADC

org.opencadc.baldur.entry = tmp
tmp.pattern = ^tmp:.*
tmp.anon = true
tmp.readWriteGroup = ivo://cadc.nrc.ca/gms?TMP-RW

org.opencadc.baldur.entry = test-compat 
test-compat.pattern = ^cadc:TEST/.*
test-compat.anon = true
test-compat.readOnlyGroup = ivo://cadc.nrc.ca/gms?Test-Read
test-compat.readWriteGroup = ivo://cadc.nrc.ca/gms?Test-Write

org.opencadc.baldur.entry = TEST-GROUPS 
TEST-GROUPS.pattern = ^cadc:TEST-GROUPS/.*
TEST-GROUPS.anon = true
TEST-GROUPS.readOnlyGroup = ivo://cadc.nrc.ca/gms?TestReadGroup-1
TEST-GROUPS.readWriteGroup = ivo://cadc.nrc.ca/gms?TestWriteGroup-1
TEST-GROUPS.readWriteGroup = ivo://cadc.nrc.ca/gms?TestWriteGroup-2
TEST-GROUPS.readWriteGroup = ivo://cadc.nrc.ca/gms?TestWriteGroup-3

org.opencadc.baldur.entry = MAST
MAST.pattern = ^mast:FOO/.*
MAST.anon = true

## CADC staff can read any file
org.opencadc.baldur.entry = CADC 
CADC.pattern = ^cadc:.*
CADC.readOnlyGroup = ivo://cadc.nrc.ca/gms?CADC
CADC.readOnlyGroup = ivo://cadc.nrc.ca/gms?StorageOps

org.opencadc.baldur.entry = IRIS 
IRIS.pattern = ^(cadc:)|(caom:)IRIS/.*
IRIS.anon = true
## for caom2-artifact-download testing
IRIS.readWriteGroup = ivo://cadc.nrc.ca/gms?CADC

