tomcat.connector.connectionTimeout=20000
tomcat.connector.keepAliveTimeout=20000
tomcat.connector.secure=true
tomcat.connector.scheme=https
tomcat.connector.proxyName=haproxy.cadc.dao.nrc.ca
tomcat.connector.proxyPort=443

ca.nrc.cadc.auth.IdentityManager=ca.nrc.cadc.ac.ACIdentityManager

## enable support for haproxy SSL termination + pass client cert
ca.nrc.cadc.auth.PrincipalExtractor.enableClientCertHeader=true

## not strictly needed since caller and grants use x509
ca.nrc.cadc.auth.IdentityManager=ca.nrc.cadc.ac.ACIdentityManager

