#!/bin/bash

SELF=$(basename $(pwd))
IMG="youcat:latest"
#IMG="images.opencadc.org/core/youcat:0.9.5"

. $HOME/bin/docker-common-setup SRC

. $HOME/bin/docker-static-ip $SELF

PG=src-youcatdb
PGIP=$(docker-find-ip $PG)

CMD="docker run --rm --user tomcat:tomcat \
	--network=$DOCKER_NET --ip=$DOCKER_STATIC_IP \
	--add-host $HAP:$HAPIP \
        --env tomcat.connector.proxyName=$HAP \
        --add-host $PG:$PGIP \
	--volume=$(pwd)/config:/config:ro \
        --name $SELF $IMG"

echo $CMD

$CMD >& tomcat.log &

if [ "$1" = "-f" ]; then
    exec tail -100f tomcat.log
fi

