
org.opencadc.torkeep.grantProvider = ivo://opencadc.org/baldur

org.opencadc.torkeep.collection = IRIS
IRIS.basePublisherID = ivo://opencadc.org/
#IRIS.computeMetadata = false 
#IRIS.proposalGroup = false

org.opencadc.torkeep.collection = TEST
TEST.basePublisherID = ivo://opencadc.org/
TEST.computeMetadata = true

#TEST = jdbc/sandboxtest-repo content caom2 Observation ivo://cadc.nrc.ca/gms?caom2TestGroupRead ivo://cadc.nrc.ca/gms?caom2TestGroupWrite ca.nrc.cadc.caom2.persistence.PostgreSQLGenerator operatorGroup=ivo://cadc.nrc.ca/gms?SC2-TEST-Operator staffGroup=ivo://cadc.nrc.ca/gms?SC2-TEST-Staff proposalGroup=true basePublisherID=ivo://cadc.nrc.ca/test

