# local registry
ca.nrc.cadc.reg.client.RegistryClient.baseURL=LOCALREG
# prod registry
ca.nrc.cadc.reg.client.RegistryClient.baseURL = https://spsrc27.iaa.csic.es/reg

# SKA IAM OpenID provider
ivo://ivoa.net/sso#OpenID = https://ska-iam.stfc.ac.uk/

## dummy values to verify invalid config
#ivo://skao.int/std/AuthAPI = foo:bar 
#ivo://skao.int/std/PermissionsAPI = bar:baz


