#
# This file maps resource identifiers to the location of capability
# information.
#
ivo://opencadc.org/reg = https://haproxy.cadc.dao.nrc.ca/reg/capabilities

## storage inventory
ivo://opencadc.org/baldur = https://haproxy.cadc.dao.nrc.ca/baldur/capabilities
ivo://opencadc.org/luskan = https://haproxy.cadc.dao.nrc.ca/luskan/capabilities
ivo://opencadc.org/raven = https://haproxy.cadc.dao.nrc.ca/raven/capabilities
ivo://opencadc.org/minoc = https://haproxy.cadc.dao.nrc.ca/minoc/capabilities
ivo://opencadc.org/alt/minoc = https://haproxy.cadc.dao.nrc.ca/alt/minoc/capabilities
ivo://opencadc.org/vault = https://haproxy.cadc.dao.nrc.ca/site/vault/capabilities
ivo://opencadc.org/site/minoc = https://haproxy.cadc.dao.nrc.ca/site/minoc/capabilities
## raven intTest support - 2 and 3 must be different services for test to work
ivo://negotiation-test-site1 = https://haproxy.cadc.dao.nrc.ca/minoc/capabilities
ivo://negotiation-test-site2 = https://haproxy.cadc.dao.nrc.ca/minoc/capabilities
ivo://negotiation-test-site3 = https://haproxy.cadc.dao.nrc.ca/alt/minoc/capabilities

ivo://opencadc.org/cred = https://haproxy.cadc.dao.nrc.ca/cred/capabilities
ivo://opencadc.org/cavern = https://haproxy.cadc.dao.nrc.ca/cavern/capabilities
ivo://opencadc.org/youcat = https://haproxy.cadc.dao.nrc.ca/youcat/capabilities
# currently needed by youcat integration test code:
ivo://cadc.nrc.ca/cadc/minoc = https://ws-cadc.canfar.net/minoc/capabilities

## caom2 local testing
ivo://opencadc.org/torkeep = https://haproxy.cadc.dao.nrc.ca/torkeep/capabilities
ivo://opencadc.org/argus = https://haproxy.cadc.dao.nrc.ca/argus/capabilities
ivo://opencadc.org/bifrost = https://haproxy.cadc.dao.nrc.ca/bifrost/capabilities
ivo://opencadc.org/dap = https://haproxy.cadc.dao.nrc.ca/dap/capabilities
ivo://opencadc.org/sia = https://haproxy.cadc.dao.nrc.ca/sia/capabilities

# CAOM-2.5
ivo://opencadc.org/caom25/torkeep = https://haproxy.cadc.dao.nrc.ca/caom25/torkeep/capabilities
ivo://opencadc.org/caom25/argus = https://haproxy.cadc.dao.nrc.ca/caom25/argus/capabilities
ivo://opencadc.org/caom25/bifrost = https://haproxy.cadc.dao.nrc.ca/caom25/bifrost/capabilities

## OIDC testing using SRCNet IAM
ivo://opencadc.org/src/cavern = https://haproxy.cadc.dao.nrc.ca/src/cavern/capabilities
ivo://opencadc.org/src/posix-mapper = https://haproxy.cadc.dao.nrc.ca/src/posix-mapper/capabilities
ivo://opencadc.org/src/youcat = https://haproxy.cadc.dao.nrc.ca/src/youcat/capabilities
ivo://opencadc.org/src/argus = https://haproxy.cadc.dao.nrc.ca/src/argus/capabilities
ivo://opencadc.org/src/bifrost = https://haproxy.cadc.dao.nrc.ca/src/bifrost/capabilities
ivo://opencadc.org/src/torkeep = https://haproxy.cadc.dao.nrc.ca/src/torkeep/capabilities


## hybrid environment most of the time
# note rely on multiple reg in cadc-registry.properties works bug logs lots of WARN
ivo://cadc.nrc.ca/gms = https://ws-cadc.canfar.net/ac/capabilities
#ivo://cadc.nrc.ca/gms = https://haproxy.cadc.dao.nrc.ca/ac/capabilities
ivo://cadc.nrc.ca/cred = https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/cred/capabilities
#ivo://cadc.nrc.ca/cred = https://haproxy.cadc.dao.nrc.ca/cred/capabilities

## external services I want to find
ivo://skao.int/reg = https://spsrc27.iaa.csic.es/reg/capabilities
ivo://skao.int/gms = https://permissions.srcnet.skao.int/api/v1/gms/capabilities
ivo://skao.int/tap = https://dachs.ivoa.srcnet.skao.int/tap/capabilities

