#!/bin/bash

SELF=$(basename $(pwd))
IMG=torkeep:caom25
IMG="images.opencadc.org/caom2/torkeep:2.0-BETA-05"

. $HOME/bin/docker-common-setup SRC

. $HOME/bin/docker-static-ip $SELF

PG=torkeep25db
PGIP=$(docker-find-ip $PG)

CMD="docker run --rm --user tomcat:tomcat \
	--network=$DOCKER_NET --ip=$DOCKER_STATIC_IP \
	--add-host $HAP:$HAPIP \
    	--add-host $PG:$PGIP \
	--volume=$(pwd)/config:/config:ro \
        --name $SELF $IMG"

echo $CMD

exec $CMD >& tomcat.log &

if [ "$1" = "-f" ]; then
    tail -100f tomcat.log
fi

