tomcat.connector.connectionTimeout=20000
tomcat.connector.keepAliveTimeout=20000
tomcat.connector.secure=true
tomcat.connector.scheme=https
tomcat.connector.proxyName=haproxy.cadc.dao.nrc.ca
tomcat.connector.proxyPort=443

# connection pool
org.opencadc.raven.query.maxActive=1
org.opencadc.raven.query.username=tapuser
org.opencadc.raven.query.password=pw-tapuser
org.opencadc.raven.query.url=jdbc:postgresql://pg15test/cadctest

org.opencadc.raven.inventory.maxActive=1
org.opencadc.raven.inventory.username=cadmin
org.opencadc.raven.inventory.password=pw-cadmin
org.opencadc.raven.inventory.url=jdbc:postgresql://pg15test/cadctest

## enable CADC IM
ca.nrc.cadc.auth.IdentityManager=ca.nrc.cadc.ac.ACIdentityManager

## enable support for haproxy SSL termination + pass client cert
ca.nrc.cadc.auth.PrincipalExtractor.enableClientCertHeader=true

#ca.nrc.cadc.util.Log4jInit.messageOnly=true

