
org.opencadc.vault.resourceID = ivo://opencadc.org/vault

org.opencadc.vault.consistency.preventNotFound = false

# vault database settings
org.opencadc.vault.inventory.schema = inventory
org.opencadc.vault.vospace.schema = vospace
org.opencadc.vault.singlePool = true 

# root container nodes
org.opencadc.vault.root.owner = pdowler

# storage namespace
org.opencadc.vault.storage.namespace = vault:

