#!/bin/bash

SELF=$(basename $(pwd))
IMG="argus:caom25"
IMG="images.opencadc.org/caom2/argus:2.0-BETA"

\rm -f config/cadcproxy.pem config/tmpops.pem
\cp ~/work/test-certificates/servops.pem config/cadcproxy.pem
#\cp ~/work/test-certificates/tmpops.pem config/tmpops.pem

. $HOME/work/bin/docker-static-ip $SELF
echo "DOCKER_STATIC_IP: $DOCKER_STATIC_IP"
echo "      DOCKER_NET: $DOCKER_NET"

\rm -f tomcat.log && touch tomcat.log

PG=torkeep25
PGIP=$(lxc list | grep $PG | awk '{print $6}')

HAP=haproxy.cadc.dao.nrc.ca
HAPIP=$(grep $HAP /etc/hosts | awk '{print $1}')

CMD="docker run --rm --user tomcat:tomcat \
	--network=$DOCKER_NET --ip=$DOCKER_STATIC_IP \
	--add-host $HAP:$HAPIP \
    	--add-host $PG:$PGIP \
	--volume=$(pwd)/config:/config:ro \
        --name $SELF $IMG"

echo $CMD

$CMD >& tomcat.log &

if [ "$1" = "-f" ]; then
    exec tail -100f tomcat.log
fi

